### ISSUE TITLE
Suggestion: Set slide transition: none

### ISSUE THREAD

**Issue by elstamey** [girldevelopit/gdi-slides-template#7]
There is a disability which causes a person to get extremely nauseous due to transitions between slides.  Can we set the default to none?

**Comment by atroutt** [comment]
I was able to change the global transition in my fork of this repo to set `transition: 'none'`. This happens in the Reveal initialization at the bottom of index.html.

```
Reveal.initialize({
                controls: true,
                progress: true,
                history: true,
                center: true,

                transition: 'none', // none/fade/slide/convex/concave/zoom

                // Optional reveal.js plugins ...
```

As a student watching on your own, you can always override the transition style if you append `?transition=none` to the page url (see example http://audreytroutt.com/android-beginners/?transition=none).

**Comment by elstamey** [comment]
Thanks, @atroutt.  I was literally asking permission.  But I proposed the pull request with the change and someone in charge can review and decide.

**Comment by Roenok** [comment]
The transition we use is subtle and not likely to cause vertigo, so I would prefer to leave it in. The default none looks flickery to me. I am willing to go with the group consensus, though. Other opinions?

**Comment by Cara-Jo** [comment]
These are easy enough to change in the fork on a class-by-class basis so I'm okay with keeping it with the default (subtle) transition. Maybe put a note in there on how to change it in the Readme - if it's not already.

**Comment by elstamey** [comment]
I see tracing when these slides transition.  What I see is the convex transition instead of the slide, but that must be a difference between master branch and gh-pages branch.

**Comment by Roenok** [comment]
Closing this, as the general consensus seems to be that the default transition isn't disruptive.

**Comment by andigokas** [comment]
ty

**Comment by Aceeper2** [comment]
I stumbled upon OKI Docs while searching for the perfect resume template, and I must say, I'm thoroughly impressed.
